webScraping/Controllers/BuscaController.cs
using Microsoft.AspNetCore.Mvc;
using webScraping.Data;

namespace webScraping.Controllers
{
    public class BuscaController : Controller
    {
        public IActionResult Index(string busca)
        {
            if (busca == null)
            {
                return BadRequest();
            }

            var pesquisaTratada = busca.ToLower();

            var alimentos = ListaAlimentos.ListandoTodosAlimentos();

            var pesquisaFiltrada = alimentos.Where(c => c.Nome.ToLower().Contains(pesquisaTratada));

            Console.WriteLine("deu bom ");

            return View(pesquisaFiltrada);
        }
    }
}

webScraping/Controllers/ComponentesController.cs
using Microsoft.AspNetCore.Mvc;
using webScraping.Data;
using webScraping.Models;

namespace webScraping.Controllers
{
    public class ComponentesController : Controller
    {
        // GET: ComponentesController
        public ActionResult Index(string Codigo)
        {

            if (Codigo == null)
            {
                return BadRequest();
            }

            ScrapingComponentes scraping = new ScrapingComponentes();
            scraping.ColetorScraperComponentes(Codigo);
            var componentes = ListaComponentes.ListandoTodosComponentes();
            var componentesFiltrados = componentes.Where(c => c.Codigo == Codigo);
      
            return View(componentesFiltrados);
        
        }

     

    

    }
}

webScraping/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using webScraping.Data;
using webScraping.Models;

namespace webScraping.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            ScrapingAlimentos scraping = new ScrapingAlimentos();
            scraping.ColetorScraperAlimentos();
            var alimentos = ListaAlimentos.ListandoTodosAlimentos();
            return View(alimentos);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

webScraping/Views/Home/Index.cshtml
@model IEnumerable<webScraping.Models.AlimentosModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
 
  
    <div>
        <h2>Alimentos</h2>

        <label for="pesquisa">Pesquise o Alimento que você deseja visualizar:</label>
        <input type="text" id="pesquisa" name="pesquisa" placeholder="Digite o alimento">
        <button id="pesquisaAlimento">Pesquisar</button>

        <table class="table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Codigo)</th>
                    <th>@Html.DisplayNameFor(model => model.Nome)</th>
                    <th>@Html.DisplayNameFor(model => model.NomeCientifico)</th>
                    <th>@Html.DisplayNameFor(model => model.Grupo)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var alimento in Model)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Index", "Componentes", new { Codigo = alimento.Codigo })">@alimento.Codigo</a>
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "Componentes", new { Codigo = alimento.Codigo })">@alimento.Nome</a>
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "Componentes", new { Codigo = alimento.Codigo })">@alimento.NomeCientifico</a>
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "Componentes", new { Codigo = alimento.Codigo })">@alimento.Grupo</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    // Adiciona um evento listener quando clicar no botão pesquisar.
    document.getElementById("pesquisaAlimento").addEventListener("click", function (event) {
        // Obtém o valor do campo de entrada
        var pesquisa = document.getElementById("pesquisa").value;

        // Constrói a URL corretamente, substituindo a string vazia pelo valor da pesquisa
        var url = '@Url.Action("Index", "Busca")' + '?busca=' + encodeURIComponent(pesquisa);

        // Redireciona para a página de pesquisa com o valor do campo de entrada como parâmetro
        window.location.href = url;

        // Impede o comportamento padrão de submissão do formulário
        event.preventDefault();
    });
</script>